FROM quay.io/3scale/s2i-openresty-centos7:1.13.6.1-rover2
LABEL maintainer="dortiz@redhat.com"

USER root

# 'default' user is defined in the base image
ARG USER_NAME=default
ARG USER_HOME=/home/centos

RUN yum -y update \
 && yum -y install sudo \
 && yum -y autoremove \
 && yum -y clean all

RUN mkdir -p ${USER_HOME}/gateway \
 && chown -R ${USER_NAME}: ${USER_HOME} \
 && echo "${USER_NAME} ALL=(ALL:ALL) NOPASSWD: ALL" > /etc/sudoers.d/${USER_NAME} \
 && chmod 0440 /etc/sudoers.d/${USER_NAME}

COPY gateway/Roverfile ${USER_HOME}/gateway
COPY gateway/Roverfile.lock ${USER_HOME}/gateway
COPY Makefile ${USER_HOME}

WORKDIR ${USER_HOME}

RUN make dependencies

COPY . ${USER_HOME}

RUN chown -R ${USER_NAME}: ${USER_HOME}
USER ${USER_NAME}
