ARG BUILDER_IMAGE
FROM ${BUILDER_IMAGE}
LABEL maintainer="dortiz@redhat.com"

USER root

# 'default' user is defined in the base image
ARG USER_NAME=default
ARG USER_HOME=/home/centos

RUN yum -y install sudo \
 && yum -y autoremove \
 && yum -y clean all

RUN mkdir -p ${USER_HOME}/gateway \
 && chown -R ${USER_NAME}: ${USER_HOME} \
 && echo "${USER_NAME} ALL=(ALL:ALL) NOPASSWD: ALL" > /etc/sudoers.d/${USER_NAME} \
 && chmod 0440 /etc/sudoers.d/${USER_NAME}

COPY gateway/cpanfile ${USER_HOME}/gateway
RUN cpanm --installdeps ${USER_HOME}/gateway

COPY gateway/Roverfile ${USER_HOME}/gateway
COPY gateway/Roverfile.lock ${USER_HOME}/gateway

WORKDIR ${USER_HOME}

RUN rover install --roverfile=gateway/Roverfile

COPY Makefile ${USER_HOME}

RUN make dependencies

COPY . ${USER_HOME}

RUN chown -R ${USER_NAME}: ${USER_HOME}
USER ${USER_NAME}
