#!/bin/sh
set -euo pipefail

coverage='luacov.stats.*.out'

generate_coverage() {
  find . -maxdepth 1 -name "$coverage" -exec script/luacov '{}' \;
}
trap generate_coverage EXIT

# shellcheck disable=SC2086
rm -f $coverage luacov.report.*.out

if [ -n "${JUNIT_OUTPUT_FILE:-}" ]; then
  mkdir -p "$(dirname "$JUNIT_OUTPUT_FILE")"
fi

if (prove "$@" 2>&1 | awk '/found ONLY/ { print "FAIL: because found ONLY in test"; print; exit 1 }; { print }'); then
  echo "Success"
else
  status="$?"
  echo "Failure. Exit code: ${status}"
  exit $status
fi
